### ISSUE TITLE
Support `file:///` URLs in AppsTab

### ISSUE THREAD

**Issue by AldoMX** [AlexStrNik/Browserino#1]
Hi, thank you for writing a native alternative to Browserosaurus.

Currently, AppsTab only supports http & https URLs:

https://github.com/AlexStrNik/Browserino/blob/8fadea345ddaa367c9079c3767589be95a0e10e1/Browserino/Views/Preferences/AppsTab.swift#L21-L29

I opened the issue to request support for `file:///` URLs.

**Comment by AlexStrNik** [comment]
Hi! Can you give me an example of what you're trying to do? File URLs don't have hosts
