### ISSUE TITLE
Slack doesn't appear in browser list

### ISSUE THREAD

**Issue by stck** [AlexStrNik/Browserino#10]
Idk what is the root cause - brew installation of Slack / builtin settings / etc - but Slack did not appear after even specifying direct locations to search on. 
Same configuration and same laptop shows different result for browserosaurus and browserino
<img width="240" alt="browserosaurus" src="https://github.com/user-attachments/assets/6613f0e6-1e8c-4bdf-8b1f-cf0694006b6b">

<img width="245" alt="browserino" src="https://github.com/user-attachments/assets/3c209ae3-fd8a-4a39-9449-3c09b10e2d0a">

(I've tried to reset all the configuration, adding search location and havent succeed).

**Comment by AlexStrNik** [comment]
Hello! I guess Slack isn't register itself for all the https links, I can check that later. Anyway, you can still add it using the Applications tab and only for Slack links and that might be even better.

**Comment by stck** [comment]
Thank you a lot, that actually worked for me
<img width="249" alt="slack after applications" src="https://github.com/user-attachments/assets/10256e27-0fcd-4411-903c-4fe93f48f514">
