### ISSUE TITLE
Feature Request: Rules Tab

### ISSUE THREAD

**Issue by Ravian18** [AlexStrNik/Browserino#12]
Version used: v1.1.6 but also not working on v1.1.5

I've setup this rule with the expectation that whenever I click a link to github.com, it automatically opens Firefox:
<img width="726" alt="image" src="https://github.com/user-attachments/assets/f9cd859f-469f-46b5-99d2-3d44a8b6db8a">

I'm however still just getting a popup to select the Browser when clicking a github.com hyperlink. What am I doing wrong?

**Comment by AlexStrNik** [comment]
Hello! So, the Apps tab was actually designed for adding apps, not browsers. Things like Slack can open links to threads, but not other websites. And adding an app still shows a pop-up if you want to open some links in the app and some on the browser.

What you're thinking of is more like the Rules tab, which I still have plans for, but unfortunately haven't implemented yet.

**Comment by AlexStrNik** [comment]
@Ravian18 just released v1.1.7 with Rules Tab, could you please check if it works for you?

**Comment by Ravian18** [comment]
@AlexStrNik my initials tests show that this works very nicely! I'll test it more thoroughly tomorrow during work. Thanks!

**Comment by Ravian18** [comment]
I just tried it using a regex but that doesn't seem to work as expected. I'm clicking a link with `jira.test.test2.com`. When adding the exact value `jira.test.test2.com` it works. When using the regex `.*\.?test2\.com$` or `.*test2\.com$` it does not work (and opens a window to select the browser).

**Comment by AlexStrNik** [comment]
<img width="705" alt="Screenshot 2024-12-03 at 11 45 14" src="https://github.com/user-attachments/assets/0ad1d0b2-30a3-42c4-a9e4-ce9194f1a9d9">

I don't think you need the trailing dollar sign, because regex works on the entire URL, not just the host, and normal URLs can have a slash at the end.

**Comment by Ravian18** [comment]
Removing the dollar sign (`.*test2\.com`) works perfect, thanks! I'll test it some more during the week

**Comment by Ravian18** [comment]
For now this looks good, no issues during testing. Will create a new ticket if stuff doesn't work so we can close this one. Thanks again!
