### ISSUE TITLE
Feature request: open links in Incognito in the supported browsers

### ISSUE THREAD

**Issue by AnimeshTalukdar** [AlexStrNik/Browserino#14]
When you click on the browser of your choice with shift key pressed down it opens in that particular browser in incognito. Or if let's say 'g' is set up as the browser shortcut key then when pressing shift+'g' instead of opening the link in a normal tab it would be opened in a incognito tab. Like it is in browserosauros

**Comment by AlexStrNik** [comment]
Hi @AnimeshTalukdar  Can you give the latest version (v1.1.8) a try? There's a little guide in the release notes on how to set it up, and you can use this file to see the argument names: https://github.com/will-stone/browserosaurus/blob/main/src/config/apps.tsI decided not to hard-code a list of browsers so anyone can add a new one without having to wait for a PR approval or anything.

**Comment by AnimeshTalukdar** [comment]
Wow man, thanks... it's working perfectly. 

![image](https://github.com/user-attachments/assets/52e8a7fc-7639-4521-a6f1-67d7ca746348)

**Comment by AlexStrNik** [comment]
You're welcome) Btw, you can hide an reorder browsers. I will close issue for now, if anything don't work as expected feel free to reopen it)

**Comment by A-Kun** [comment]
How about Firefox?
