### ISSUE TITLE
Handoff doesn't work properly

### ISSUE THREAD

**Issue by fedorareis** [AlexStrNik/Browserino#3]
When I try to hand off a website from my phone I get the Browserino icon in my dock but when I click on it the icon just disappears instead of prompting for which browser to open the website in.

Brwoserino version: v1.1.1
OS Version: 15.0.1

**Comment by AlexStrNik** [comment]
Hello! Could you record video please? I tried to replicate bug, but it worked for me

**Comment by fedorareis** [comment]
Here is a video. If there is any other information I can provide let me know.
https://github.com/user-attachments/assets/260fd86c-3cf5-4e20-98cc-2e52ef9878dd

**Comment by AlexStrNik** [comment]
@fedorareis Hello! Fixed in release v1.1.3. Note that I have also changed the distribution format, as I plan to write a Brew cask in the near future.

**Comment by fedorareis** [comment]
That worked. Thank you.
