### ISSUE TITLE
Inquiry to explain a block of code and a request for a new feature.

### ISSUE THREAD

**Issue by byt3m4st3r** [AlexStrNik/Browserino#5]
Hi,

I like your app and your improvements, especially the new feature to hide browsers.

But, there is a part of code I do not understand, can you explain what the following block of code is relevant for — see link below from line 117 to 128?

https://github.com/AlexStrNik/Browserino/blob/955724d1db20c90b88cdbdeeff42e3e268a092e3/Browserino/Views/Preferences/EditAppForm.swift#L117

Btw, it would also be a cool feature to make the browser locations configurable, f.e. for company usage, where browsers could be located under a ~/Applications or under a ~/opt/… folder.

Regards and thanks.

**Comment by AlexStrNik** [comment]
Oh, thats SwiftUI Preview https://www.avanderlee.com/swiftui/previews-different-states/. You probably confused by hardcoded application and link, but don't worry that code even not shipped in binary) It just for me to test that form looks and behaves as it planned to be

And thanks for suggestion i will implement it a bit later

**Comment by byt3m4st3r** [comment]
Thanks for clarification.
