### ISSUE TITLE
Sequoia and Slack - missing Browserino window

### ISSUE THREAD

**Issue by michalg-** [AlexStrNik/Browserino#7]
Hi, I recently updated my Mac to Sequoia and noticed an issue with Slack. Browserino works in every other app. It seems like it tries to show up—the focus changes for a moment—but the window doesn't appear.

https://github.com/user-attachments/assets/c03fee7b-5340-4d38-9151-66b6fd962c03

**Comment by AlexStrNik** [comment]
Heck, that's going to be hard to debug. What if you change the default browser to something else (like Safari)? Will the link still open? I guess maybe Slack is bugged itself, or it's preventing the opening to show a dialog or something.

**Comment by RichGuk** [comment]
I'm also experiencing this issue. If it helps, I'm still on Sonoma. It works in other applications other than Slack.

Browserosaurus doesn't have this issue with Slack.

**Comment by Ravian18** [comment]
It is not a bug in Slack, if I set my default browser to Brave the link opens just fine. It also works when using Browserosaurus. Let me know if you want me to test anything :)

**Comment by AlexStrNik** [comment]
For some reason, Slack keeps focusing after you click on a link. I released version 1.1.4, hoping it will help (and hopefully it won't break any other apps). @RichGuk @michalg- @Ravian18  Can you please test it if you have the time and let me know if it's working for you?

**Comment by michalg-** [comment]
Sure, when dmg should be available?

**Comment by Ravian18** [comment]
@AlexStrNik only source code seem available. Any chance on a .dmg or .zip with the Application?

**Comment by AlexStrNik** [comment]
Sorry! Uploaded, can you check now?

**Comment by Ravian18** [comment]
Works using Slack now, great! Haven't noticed any other apps not working anymore as well, thanks!

**Comment by RichGuk** [comment]
@AlexStrNik Working for me too. Thanks!
